brief updates
HackCU/LocalHackDay2016 pull request #42
Opened 2019-09-26 23:26 UTC by peasant98

## Description
Brief updates to info for local hack day. More to come, e.g., update to schedule, design change, etc.

## Related Issues
a new year

## Some questions
1. Did you read the contributing guidelines?
	Ye
2. Did you edit any CSS or JS file?
	No
3. If you answered yes, did you update the version number on `index.html`?
If you answered No to question 1, go back and read the [instructions](.github/CONTRIBUTING.md) carefully.
If you answered Yes to question 2 and No to question 3, go back and update the version number.

## Additional Notes
Do you want to add anything else? We :heart: to hear your opinions!

Mamba Mentality

2019-09-29 22:28 UTC, lucca requested changes
constantly try to make the website the best version of itself also I added 2 single characters I think would fit better but the rest is good

2019-09-29 22:28 UTC, lucca commented on _data/faq.yaml
> +  answer: No, everyone attending Local Hack Day should be local. If you're out of state, check out [HackCU V](https://hackcu.org), where we offer reimbursement!
answer: No, everyone attending Local Hack Day should be local. If you're out of state, check out [HackCU VI](https://hackcu.org), where we offer reimbursements!

2019-09-30 00:12 UTC, peasant98 reviewed
addressed two characters

2019-09-30 03:37 UTC, lucca approved these changes

2019-09-30 03:37 UTC, merged